version: '3.8'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./config/process.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./config/pgadmin.env
    ports:
      - "80:80"
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres